### ISSUE TITLE
#[xactor::main] Main not working

### ISSUE THREAD

**Issue by alborq** [sunli829/xactor#10]
Hello, when i try to use macro : `#[xactor::main]`
App dont build,
I get this error : 

```
error: macros that expand to items must be delimited with braces or followed by a semicolon
 --> src/main.rs:4:1
  |
4 | / async fn main() -> Result<()> {
5 | |     Ok(())
6 | | }
  | |_^
  |
help: change the delimiters to curly braces
  |
4 | {
5 | }
  |
help: add a semicolon
  |
6 | };
  |  ^

error: macro expansion ignores token `,` and any following
 --> src/main.rs:4:1
  |
3 |   #[xactor::main]
  |   --------------- caused by the macro expansion here
4 | / async fn main() -> Result<()> {
5 | |     Ok(())
6 | | }
  | |_^
  |
  = note: the usage of `xactor::main!` is likely invalid in item context

error: main function cannot have a return value
 --> src/main.rs:4:1
  |
4 | / async fn main() -> Result<()> {
5 | |     Ok(())
6 | | }
  | |_^

warning: unused import: `xactor::*`
 --> src/main.rs:1:5
  |
1 | use xactor::*;
  |     ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0601]: `main` function not found in crate `popdb`
 --> src/main.rs:1:1
  |
1 | / use xactor::*;
2 | |
3 | | #[xactor::main]
4 | | async fn main() -> Result<()> {
5 | |     Ok(())
6 | | }
  | |_^ consider adding a `main` function to `src/main.rs`

error: aborting due to 4 previous errors; 1 warning emitted
```

My test  code is pretty simple 
```
use xactor::*;

#[xactor::main]
async fn main() -> Result<()> {
    Ok(())
}
```

I dont see where it fail and how fix... cant make a proposal.

**Comment by sunli829** [comment]
Let me see what's going on.

**Comment by sunli829** [comment]
I tried it and it worked, and the example can compiled. 😐

**Comment by alborq** [comment]
Strange, i retry on an empty project, i got a same error, i try to create an exemple repository and see if i can reproduce on github build action. 

while i did it, i can give u this : 
```
root@60e740e606c2:/test/foo# rustc --version
rustc 1.43.1 (8d69840ab 2020-05-04)
root@60e740e606c2:/test/foo# cargo --version
cargo 1.43.0 (2cbe9048e 2020-05-03)
```
If some extra info can be usefull, tell me.

**Comment by sunli829** [comment]
The main function cannot have a return value.😂

**Comment by alborq** [comment]
Xactor main ^^

Rust allow it : https://doc.rust-lang.org/stable/rust-by-example/error/result.html#using-result-in-main 

Async-std too, like ping exemple : 
https://github.com/sunli829/xactor/blob/master/examples/ping.rs

Maybe macro need some change to allow it too ? 
---
(for archive)
A failed build with this problem: https://github.com/sunli829/xactor/pull/11/checks?check_run_id=731182132

**Comment by sunli829** [comment]
Ok, I'll add this to it.

**Comment by sunli829** [comment]
Please upgrade to `0.7`.

**Comment by alborq** [comment]
Not Ok for me... 

with this code : 
```
use xactor::*;

#[xactor::main]
async fn main() -> Result<()> {
    Ok(())
}
```

I get : 
```
error[E0308]: mismatched types
 --> src/main.rs:4:20
  |
3 | #[xactor::main]
  | --------------- implicitly returns `()` as its body has no tail or `return` expression
4 | async fn main() -> Result<()> {
  |                    ^^^^^^^^^^ expected enum `std::result::Result`, found `()`
  |
  = note:   expected enum `std::result::Result<(), anyhow::Error>`
          found unit type `()`

```

**Comment by sunli829** [comment]
Did you not upgrade `xactor`?

**Comment by alborq** [comment]
I have move to 0.7, I wanna check why ping exemple work but CI is broken on master (I thinks it not, try on my computer)

**Comment by sunli829** [comment]
The CI configuration is wrong. 😂

**Comment by alborq** [comment]
Soo.. 
```shell
root@60e740e606c2:/srv# cargo init foo
     Created binary (application) package
root@60e740e606c2:/srv# cd foo/
root@60e740e606c2:/srv/foo# cargo add xactor 
    Updating 'https://github.com/rust-lang/crates.io-index' index
      Adding xactor v0.7.0 to dependencies
root@60e740e606c2:/srv/foo# nano src/main.rs 
    #copy paste empty.rs
root@60e740e606c2:/srv/foo# cargo build 
    Updating crates.io index
    [...]
    Compiling xactor v0.7.0
    Compiling foo v0.1.0 (/srv/foo)
error[E0308]: mismatched types
 --> src/main.rs:4:20
3 | #[xactor::main]
  | --------------- implicitly returns `()` as its body has no tail or `return` expression
4 | async fn main() -> Result<()> {
  |                    ^^^^^^^^^^ expected enum `std::result::Result`, found `()`
  = note:   expected enum `std::result::Result<(), anyhow::Error>`
          found unit type `()`
```

I try `cargo expand` to understand..
```rust
#![feature(prelude_import)]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std;
use xactor::*;

async fn __main() -> Result<()> { Ok(()) }
fn main() -> Result<()> { }

```
It seen __main is not call on main... 
if we look at : https://github.com/sunli829/xactor/blob/master/xactor-derive/src/lib.rs#L77-L86 
It miss part with feature flagged. 

I'm dont really inderstand all of complexity of cargo, but i suppose : 
`xactor `and` xactor-derive` is two different package 
`xactor-derive` dont have feature definition
soo` x-actor-derive` dont inherits of cfg ability 

in exemple case, all  is embed with directory path linking, 
i suppose cargo dont have same behavior on it.

**Comment by sunli829** [comment]
> I'm dont really inderstand all of complexity of cargo, but i suppose :
> xactor and xactor-derive is two different package
> xactor-derive dont have feature definition
> soo x-actor-derive dont inherits of cfg ability

That should be the problem. Let me change it.

**Comment by sunli829** [comment]
Please upgrade to '0.7.1'. 😁

**Comment by alborq** [comment]
Working, i close but suggest : 
- change exemple for : 1 dir => 1 exemple, with cargo.toml definition,
- use PR when change for ensure test suite is valid (some release what buggy, on last days)
