### ISSUE TITLE
How to test for effects in handlers?

### ISSUE THREAD

**Issue by D1plo1d** [sunli829/xactor#33]
I'm just getting started with xactor and starting to think about how I'll unit test later on.

It looks like Context can be used to create effects with functions like `send_later` and `send_interval`. How would a unit test verify that a handler requests an effect like send_interval in a particular scenario?

**Comment by sunli829** [comment]
I think we can simulate `send_later` by sending a message directly with `send`?

**Comment by D1plo1d** [comment]
That makes sense. I took some time to get better acquainted with XActor before replying - having integrated XActor I'm no longer concerned about this.

In my initial post I was viewing actor model through the lens of [redux-loop and the elm architecture](https://redux-loop.js.org/). Because XActor handles commands sequentially has some similarity to reducers however it differs in that the command handlers are not pure functions. My question related to tests that verified a given handler created a specific list of effects (analogous to if a handler returning a list of inert futures) which was something I'd grown used to in redux-loop. Now that I'm used to XActor though this does not feel pressing.

This kind of functionality could be added as a separate library if it was useful with some kind of `xactor-reducer` that takes pure functions and executes effects (eg. send_later and send_interval) based on the reducer results but unlike Javascript where those tests were crucial to my work (and sanity at times XD) I don't feel the same pressing need for that within the safety of rust.
