### ISSUE TITLE
Documentation: How best to handle errors in handler?

### ISSUE THREAD

**Issue by D1plo1d** [sunli829/xactor#34]
What is best practice for when a handler encounters an error in the actor model? Is it better that I return a `#[message(result = "Result<()>")]` or is it better to stop the Actor and let the Supervisor restart it? When is each approach better?

**Comment by sunli829** [comment]
I think which method to use depends on whether the error you encounter is unrecoverable. If it is, it may be easier to restart the `Actor`. Otherwise, it should return a `Result`.
