### ISSUE TITLE
Subscription system doesn't play well with System::wait_all()

### ISSUE THREAD

**Issue by mabysh** [sunli829/xactor#4]
Consider example:
```rust
use xactor::*;

#[message]
#[derive(Clone)]
struct Die;

struct MyActor;

#[async_trait::async_trait]
impl Actor for MyActor {
    async fn started(&mut self, ctx: &Context<Self>) {
        ctx.subscribe::<Die>().await.unwrap();
    }
}

#[async_trait::async_trait]
impl Handler<Die> for MyActor {
    async fn handle(&mut self, ctx: &Context<Self>, _msg: Die) {
        // Stop the actor without error
        ctx.stop(None);
    }
}

#[xactor::main]
async fn main() {
    MyActor.start().await;

    Broker::from_registry().await.publish(Die).unwrap();
}
```
Here main() never returns because there is a `Broker` in registry for `Die` message. Workaround may be to store broker's `Addr` somewhere and stop it explicitly when needed but then it becomes a user responsibility and may be confusing without documentation.

So my proposition will be either handle `Broker`s lifecycle inside crate or update documentation so users know about theirs responsibility. What do you think?

**Comment by sunli829** [comment]
The Broker is an actor that keeps running so that System::wait_all cannot exit. The Service should not add an active actor count to solve this problem.
